//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birimler
    {
        public Birimler()
        {
            this.Personeller = new HashSet<Personeller>();
            this.Yetkiler = new HashSet<Yetkiler>();
        }
    
        public int birimId { get; set; }
        public string birimAd { get; set; }
    
        public virtual ICollection<Personeller> Personeller { get; set; }
        public virtual ICollection<Yetkiler> Yetkiler { get; set; }
    }
}
