//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isler
    {
        public int isId { get; set; }
        public string isAd { get; set; }
        public string isAciklama { get; set; }
        public Nullable<System.DateTime> isTarih { get; set; }
        public Nullable<int> isPersonelId { get; set; }
        public Nullable<System.DateTime> iletilenTarih { get; set; }
        public Nullable<System.DateTime> yapilanTarih { get; set; }
        public string isDurum { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
