//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsTakipDBEntities : DbContext
    {
        public IsTakipDBEntities()
            : base("name=IsTakipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Birimler> Birimler { get; set; }
        public DbSet<Isler> Isler { get; set; }
        public DbSet<Personeller> Personeller { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Yetkiler> Yetkiler { get; set; }
        public DbSet<YetkiTurler> YetkiTurler { get; set; }
    }
}
