//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public Personeller()
        {
            this.Isler = new HashSet<Isler>();
            this.Yetkiler = new HashSet<Yetkiler>();
        }
    
        public int personelId { get; set; }
        public string personelAd { get; set; }
        public Nullable<int> personelBirimId { get; set; }
        public string personelKullaniciAd { get; set; }
        public string personelParola { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual ICollection<Isler> Isler { get; set; }
        public virtual ICollection<Yetkiler> Yetkiler { get; set; }
    }
}
