//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YetkiTurler
    {
        public YetkiTurler()
        {
            this.Yetkiler = new HashSet<Yetkiler>();
        }
    
        public int yetkiTurId { get; set; }
        public string yetkiTurAd { get; set; }
    
        public virtual ICollection<Yetkiler> Yetkiler { get; set; }
    }
}
