//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkiler
    {
        public int yetkiId { get; set; }
        public Nullable<int> personelId { get; set; }
        public Nullable<int> birimId { get; set; }
        public Nullable<int> yetkiTurId { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual YetkiTurler YetkiTurler { get; set; }
    }
}
