//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Durumlar
    {
        public Durumlar()
        {
            this.Evraklar = new HashSet<Evraklar>();
            this.Raporlar = new HashSet<Raporlar>();
        }
    
        public int durumId { get; set; }
        public string durumAd { get; set; }
    
        public virtual ICollection<Evraklar> Evraklar { get; set; }
        public virtual ICollection<Raporlar> Raporlar { get; set; }
    }
}
