//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvrakTakipDBEntities : DbContext
    {
        public EvrakTakipDBEntities()
            : base("name=EvrakTakipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Durumlar> Durumlar { get; set; }
        public DbSet<Evraklar> Evraklar { get; set; }
        public DbSet<Personeller> Personeller { get; set; }
        public DbSet<Raporlar> Raporlar { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Yerler> Yerler { get; set; }
        public DbSet<Yetkiler> Yetkiler { get; set; }
    }
}
