//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public Personeller()
        {
            this.Raporlar = new HashSet<Raporlar>();
        }
    
        public int perId { get; set; }
        public string perAd { get; set; }
        public string perKullanici { get; set; }
        public string perParola { get; set; }
        public Nullable<int> perYetkiId { get; set; }
    
        public virtual Yetkiler Yetkiler { get; set; }
        public virtual ICollection<Raporlar> Raporlar { get; set; }
    }
}
