//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporlar
    {
        public int raporId { get; set; }
        public Nullable<int> personelId { get; set; }
        public Nullable<int> evrakId { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> durumId { get; set; }
        public Nullable<int> yerId { get; set; }
    
        public virtual Durumlar Durumlar { get; set; }
        public virtual Evraklar Evraklar { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Yerler Yerler { get; set; }
    }
}
